#!/bin/sh
git --work-tree=/var/proxy --git-dir=/var/git/proxy.git checkout -f
cp -r /var/proxy/hooks /var/git/proxy.git
docker rmi proxy_image
docker build -t proxy_image /var/proxy
docker stop proxy
docker rm proxy
docker run --restart=always \
  -i -t -d \
  -p 80:80 \
  -p 443:443 \
  -v /var/certs:/var/certs
  --name proxy \
  --net webserver_default \
  --net mailserver \
  --net regapp_network \
  proxy_image
